### PR TITLE
Handle 404s on the refreshcookie preflight more gracefully

### LINKED ISSUE #21: Be resiliant to a 404 on the refreshcookie route
When OAuth isn't present (either off or non-existent in old versions of the the LMS) the refreshcookie route returns a 404. We should soft-fail in that case and not keep trying for the lifetime of the tab.

We should consider soft-failing for non-404 errors as well because if auth is down there's no need to break things that wouldn't depend on it otherwise (e.g. copycat.)

### PR DESCRIPTION
**Pull request by j3parker**
This is per-tab. 404 should only happen prior to OAuth2 and while a tab could exist across a release it wouldn't be trying to call any APIs exclusively auth'd with OAuth2. The OAuth2 cookie is not required by the core LMS for its APIs.

This closes #21

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -13,6 +14,11 @@ function addHeaders(req) {
...
 
 function processRefreshResponse(err, res) {
+	// Prior to OAuth 2 support the refreshcookie route returns 404.
+	if(res.status == 404) {
+		global.D2LOAuth2Disabled = true;
+		return;
+	}
 
 	// In the future we should log an error
 	if(err || !res.ok) {
```
Comment (j3parker) [inline index.js]: As an aside, it would be maybe cool if this raised a JS event. The UI could pop up a notification saying "hm, things might not be working at the moment"

(Just a thought, not relevant to this issue.)

**Comment by j3parker** [comment]
Manually tested on 10.3 (sp-dev) and 10.4 with feature toggle off and on, behaviour was as-expected in each case.

File: index.js [hunk 2]
```diff
@@ -1,6 +1,7 @@
 'use strict';
 
 global.D2LAccessTokenExpiresAt = 0;
+global.D2LOAuth2Disabled = false;
```
Comment (dlockhart) [inline index.js]: Don't know if you actually need to attach this to the `global` object (or the expiry time variable for that matter).

File: index.js (hunk 1 above)
Comment (dlockhart) [inline index.js]: Yeah, interesting. Worth exploring further once we have a use case to handle it.

File: index.js (hunk 2 above)
Comment (dlockhart) [inline index.js]: Hmm, I guess other than to facilitate testing.

Comment (j3parker) [inline index.js]: I'm not 100% sure I remember why we did it but some guesses:

- Communicating across multiple copies of this library
   - Dubious: shouldn't do that and also the savings are low.
- Makes testing possible
   - Dubious, but what would be the most JS'y way to do this? add some properties onto module.exports?

Comment (dlockhart) [inline index.js]: For testing, yeah you could add methods to `module.exports` called something like `_setAccessTokenExpiry()` and `_setOAuthIsDisabled()` that just manipulate those local variables.

Comment (j3parker) [inline index.js]: cool, done.

**Comment by j3parker** [comment]
Hey @dlockhart , :shipit:?

**Comment by dlockhart** [comment]
Sorry sorry didn't notice the updates, looks good! :shipit:
